# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Building..."
- stage: parallel1
  dependsOn: Build
  jobs:
  - deployment: deploy
    displayName: Parallel deploy 1
    environment: Para 1
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo parallel job 1
              displayName: "Para Job 1"
- stage: Test2
  dependsOn: Build
  jobs:
  - deployment: deploy
    displayName: Parallel deploy 2
    environment: Para 2
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo parallel job 2
              displayName: "Para Job 2"
- stage: Deploy
  dependsOn: 
  - Test1
  - Test2
  jobs:
  - job: Exit
    steps:
    - script: echo "exiting"